### ISSUE TITLE
Spelling mistake in Warehousing

### ISSUE THREAD

**Issue by vigneshs-dev** [SRIRAM-PALANIVEL-B/Capstone-Project-No-1-#1]
Hi @SRIRAM-PALANIVEL-B ,
I haven't gone through your code. The first thing catches my eye is the spelling mistake in the heading. So only I want to let you know. 
My suggestion is you can show the dashboard along with the code in GitHub. That's all.

**Comment by SRIRAM-PALANIVEL-B** [comment]
Thanks for the information, I'll change accordingly
